/*/{Protheus.doc} MT120BRW
Ponto de entrada no MATA120
Adicionar botões no browse dos pedidos de compra
@type function
@version P12
@author João Carlos da Silva
@since 24/05/2023
/*/
User Function MT120BRW() //ExecBlock("MT120BRW",.F.,.F.)

AAdd(aRotina,{"Impressao Grafica GPK", "U_GPKCOM02", 0, 2, 0, Nil}) //Impressao Grafica GPK

Return
//-----------------------------------------------------------------------------
